name: Setup Java and Maven

on:
  workflow_dispatch:  # Manual trigger, can be triggered from GitHub UI

jobs:
  setup-java-and-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # You can change this to the Java version you need

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # Maven local repository location
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install Maven
        run: |
          sudo apt-get install -y maven
